---
# https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html#deb-repo
  - name: ElasticSearch | Dependencies
    apt:
      name:
        - apt-transport-https
        - gnupg2
      state: present
    become: yes
    tags:
     - elasticsearch

  - name: ElasticSearch | apt key
    apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present

  - name: ElasticSearch | apt repo
    apt_repository:
      repo: "deb https://artifacts.elastic.co/packages/{{ elasticsearch_family }}/apt stable main"
      state: present
      update_cache: true

  - name: ElasticSearch | install
    package:
      name: elasticsearch
      state: present
    when: elasticsearch_version is not defined
    become: yes
    tags:
     - elasticsearch

  - name: ElasticSearch | install version
    package:
      name: "elasticsearch={{ elasticsearch_version }}"
      state: present
    when: elasticsearch_version is defined
    become: yes
    tags:
     - elasticsearch

  - name: ElasticSearch | configure
    template:
      src: "{{ item }}.j2"
      dest: /etc/elasticsearch/{{ item }}
      owner: root
      group: elasticsearch
      mode: 0660
    with_items:
      - jvm.options
    become: yes
    tags:
     - elasticsearch

  - name: ElasticSearch | force restart.
    service:
      name: elasticsearch
      state: restarted
      enabled: yes
    when: docker_test is not defined
    become: yes
    tags:
     - elasticserch
